dist: trusty
language: node_js
cache: yarn
node_js:
- '6.10'
- '7'
- '8'
install:
- yarn install --frozen-lockfile
before_install:
# Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
script:
- yarn test
