# Use the fully virtualised infra not for sudo, but since their container
# infra's 4GB of RAM is not sufficient to prevent yarn bootstrap OOMs:
# https://github.com/guigrpa/oao/issues/51
# https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
sudo: required
dist: trusty
language: node_js
cache: yarn
node_js:
- '6'
- '8'
- '9'
before_install:
# Use newer yarn than that pre-installed in the Travis image.
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --frozen-lockfile
- yarn link:all
script:
- yarn validate:eslintrc
- yarn lint
- yarn build
- yarn test:all
